### ISSUE TITLE
Moderation and Account Management

### ISSUE THREAD

**Issue by DonaldTsang** [fish-inu/urbandict#11]
- [ ] Logins to add entries
  - [ ] Registration with Username, Password and Email for backup
  - [ ] Login
  - [ ] submit terms
  - [ ] add definition
  - [ ] vote (and the user vote info should be internal, externals can only see number of votes)
  - [ ] add comment (see #10)
  - [ ] edit or delete comment
  - [ ] add alias (see #10)
  - [ ] vote alias (see #10)
  - [ ] add hypernyms/supersets (see #10)
  - [ ] vote hypernyms/supersets (see #10)
- [ ] moderation, since people would like to spam their way into the system to sell ads, troll or rig votes
  - [ ] Moderator and Admin flag to identify user power
  - [ ] regex or keyword based spam text (term/definition/comment) detection
  - [ ] vote or comment spam bot detection
